version: "3"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./homeassistant:/config
      - /mnt/hdd/cameras:/media/cameras:ro
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Paris

  influxdb:
    container_name: influxdb
    image: influxdb:2.6
    volumes:
      - /mnt/hdd/influxdb:/var/lib/influxdb2
    ports:
      - "8086:8086"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - /mnt/hdd/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      
  nodered:
    container_name: nodered
    image: nodered/node-red:latest
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
    environment:
      - TZ=Europe/Paris

  samba:
    container_name: samba
    image: dperson/samba
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/hdd/photos:/photos
      - /mnt/hdd/cameras:/cameras:ro
      - ./samba/smb.conf:/etc/samba/smb.conf:ro
    environment:
      - TZ=Europe/Paris
    command: -u "photos;photos123" -u "camera;camera123" -n

  ftp:
    container_name: ftp
    image: delfer/alpine-ftp-server
    restart: unless-stopped
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - /mnt/hdd/cameras:/home/camera
    environment:
      - USERS=camera|camera123|/home/camera
      - ADDRESS=192.168.1.133
      - MIN_PORT=21000
      - MAX_PORT=21010

# <<< networks doit être **hors de services**, à la racine du fichier
networks:
  solar-macvlan:
    external: true
