{
 "title": "Solar PV System",
 "description": "Iammeter Solar PV System,\r\nYou can monitor the energy flow of the solar pv system.\r\n",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "from(bucket: \"Homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"chargesPV\")\n  |> filter(fn: (r) => r._field == \"puissance_consomme\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"inverter_power\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    },
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "from(bucket: \"Homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"chargesPV\")\n  |> filter(fn: (r) => r._field == \"puissance_produite\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"inverter_power\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    },
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "from(bucket: \"Homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"chargesPV\")\n  |> filter(fn: (r) => r._field == \"puissance_injectee\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"inverter_power\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    }
   ]
  },
  {
   "title": "Today",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_daily" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
     ]
    },
    {
     "alias": "Yield Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "yield_energy_daily" }
     ]
    },
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "grid_consumption_energy_daily" }
     ]
    },
    {
     "alias": "Self-consumption rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "self_consumption_rate_daily" }
     ]
    }
   ]
  },
  {
   "title": "This Month",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_monthly" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_monthly" }
     ]
    },
    {
     "alias": "Yield Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "yield_energy_monthly" }
     ]
    },
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "grid_consumption_energy_monthly"
      }
     ]
    },
    {
     "alias": "Self-consumption rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "self_consumption_rate_monthly" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "from(bucket: \"Homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smart_meter_fronius\")\n  |> filter(fn: (r) => r._field == \"current_total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"inverter_power\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    },
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "from(bucket: \"Homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smart_meter_fronius\")\n  |> filter(fn: (r) => r._field == \"current_A\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"inverter_power\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    },
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "from(bucket: \"Homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smart_meter_fronius\")\n  |> filter(fn: (r) => r._field == \"current_B\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"inverter_power\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    },
    {
     "alias": "Inverter Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "W",
     "query": "from(bucket: \"Homeassistant\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"smart_meter_fronius\")\n  |> filter(fn: (r) => r._field == \"current_C\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"inverter_power\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "inverter_power" }
     ]
    }
   ]
  },
  {
   "title": "Yield",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_daily" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "grid_consumption_energy_daily" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Yield",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_hourly" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_hourly" }
     ]
    }
   ]
  },
  {
   "title": "Energy blance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "grid_consumption_energy_daily" }
     ]
    },
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_daily" }
     ]
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "grid_consumption_energy_hourly" }
     ]
    },
    {
     "alias": "Direct self-use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "selfuse_energy_hourly" }
     ]
    }
   ]
  },
  {
   "title": "Energy blance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Grid Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "grid_consumption_energy_hourly" }
     ]
    },
    {
     "alias": "Exported Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "exported_energy_hourly" }
     ]
    }
   ]
  },
  {
   "title": "Solar System",
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 37 },
   "options": {
    "content": "<div  id='write'  class = 'is-node'><p>\r\n<span>By installing only one WEM3080T (three phase WiFi energy meter) in your single phase solar system, and clamping the first CT onto grid, the second CT onto solar inverter and the third CT onto load if applicable, you can monitor &quot;Grid Consumption Energy&quot; (the energy consumed from the grid), &quot;Exported Energy&quot; (the energy exported to the grid) and the energy produced by solar inverter. You can monitor the energy flow of the solar system.</span></p><p><span>Enjoy and have fun on </span>\r\n<a href='https://www.iammeter.com/doc/iammeter/monitoring-quickstart-wem3080t.html' target='_blank'><span>Iammeter</span></a></p>\r\n<p><img src=\"https://leweidoc.oss-cn-hangzhou.aliyuncs.com/lewei50/img/lwkits/YNM3000iammeter-33-20190809-L2.jpg\" referrerpolicy=\"no-referrer\" alt=\"img\"></p></div>"
   }
  }
 ]
}